### ISSUE TITLE
Styling using card_mod

### ISSUE THREAD

**Issue by JeeDeWee** [zeronounours/lovelace-energy-entity-row#1]
**Some love for this card/row**
I really love this card and I am using it to show numeric values on my custom energy dashboard. You can use the date-picker and show numerical values. I do not understand why this frontend extensions gets so little stars and love.

**How to style this row using card_mod**
To adjust some of the styling I would really like to use card_mod. However, the styling of this card seems very different and I cannot get this to work.

**What did I try?**
I have looked at [this fantastic thread](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1188) with examples on how to style a normal entity row in the entities card. This does not seem to work on this special card.

I am trying to hide the icon using this code but I cannot make it work.
```
    type: entities
    entities:
      - type: custom:energy-entity-row
        name: Zonnepanelen opbrengst
        entity: sensor.zonnepanelen_besparing_totaalteller
        icon: mdi:cash-clock
        unit_of_measurement: €
        card_mod:
          style:
            hui-generic-entity-row:
              $: |
                state-badge {
                  display: none;
                }            
```
I have tried to make sense of the DOM using my browser developer window but I do not really see what I am doing wrong or how I should change my approach

**Comment by zeronounours** [comment]
Hello, after some investigations, I think it is related to https://github.com/thomasloven/lovelace-card-mod/issues/201.

I could only style the first appearing error message. This card works like conditionals to show: it first load energy stats prior to changing the content. It seems that card-mod do not track card changes anymore and then do not inject the CSS upon changes.
