### ISSUE TITLE
When a data point is missing from the statistics table too large values can be shown

### ISSUE THREAD

**Issue by rrozema** [zeronounours/lovelace-energy-entity-row#2]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:** 
v1.0.0

**Last working release (if known):**
N/A

**Browser and Operating System:**
any

**Description of problem:**
When the sensor has been unavailable for some time, entries in the statistics will be missing for the entity. or in other words: a gap exists in the statistics available for this entity. When this gap spans the start of the period selected in the date-picker, the value shown is the [sum] value of the first data row that is available inside the selected period, plus the sum of the differences between the next data points until the end of the range selected: if the statistics have been running for a while a very high value can be shown only when the starting point falls within the gap, when in the date-picker another starting point is selected for which the starting value can be determined this large value will NOT be shown, even when the starting point is before the gap and the end point is after it.

Expected behavior is that if the data at the start of the selected period is missing, an alternative starting point is selected and the difference is calculated from there. One possible approach could be to always use the very last data point available at or before the start of the selected period as the 1st data point. Or, to prevent showing the same value in multiple ranges, the starting point can be determined as the first data point that is at or after the selected period. However, in case of a missing data point this will skip the very first entry from the selected range; the value will be a little bit to low.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I have worked around the issue for my data by running a sql query that inserts any missing rows into the statistics table. The query I wrote for this is in the HA forum: [https://community.home-assistant.io/t/sql-to-insert-missing-statistics-rows/727467](https://community.home-assistant.io/t/sql-to-insert-missing-statistics-rows/727467)

**Comment by zeronounours** [comment]
It is not really a bug, as its the way HA implement statistic. It is not possible to differentiate (in the frontend part) a device which was off for a long period from a device which stops sending data (hence not consuming energy from HA standpoint).

It's the reason HA has implemented an adjust API. What's missing is a front end to easily do what you did in your SQL query: update many statistics with a linear regression between 2 points in time.
