### ISSUE TITLE
No entities in the enties card after upgrading to 2024.12.0

### ISSUE THREAD

**Issue by riohHA** [zeronounours/lovelace-energy-entity-row#3]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.00
**Last working release (if known):**

**Browser and Operating System:**
Chrome and Edge, on Windows 11
Core 2024.12.0
Supervisor 2024.11.4
Operating system 14.0
Frontend 20241127.4

**Description of problem:**
After installing Core 2024.12.0, the entities cards are empty, (I can still see the entities in edit mode)

**Javascript errors shown in the web inspector (if applicable):**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'styleSheet')
    at energy-entity-row.js?hacstag=640556013100:11:2978
    at Array.map (<anonymous>)
    at energy-entity-row.js?hacstag=640556013100:11:2939
    at kt.createRenderRoot (energy-entity-row.js?hacstag=640556013100:11:3142)
    at kt.createRenderRoot (energy-entity-row.js?hacstag=640556013100:23:151)
    at kt.connectedCallback (energy-entity-row.js?hacstag=640556013100:11:3253)
    at kt.connectedCallback (energy-entity-row.js?hacstag=640556013100:23:737)
    at kt.connectedCallback (energy-entity-row.js?hacstag=640556013100:39:4762)
    at t.connectedCallback (scoped-custom-element-registry.js:248:42)
    at $.k (lit-html.ts:1411:53)
```

**Additional information:**
After returning back to Core 2024.11.3, it worked again!

**Comment by rrozema** [comment]
![Screenshot_2024-12-07-12-42-47-241_io homeassistant companion android](https://github.com/user-attachments/assets/f59ce8c8-0fee-40ea-9f94-f9facbcca670)
Here's what it looks like for me: none of the entities are shown anymore. I would love to get this back in operation, as this screen gave me great insights on energy used, produced and the costs and income over a selected period

**Comment by rrozema** [comment]
Thanks a lot. To confirm it works again: 
![Screenshot_2024-12-09-09-19-56-917_io homeassistant companion android](https://github.com/user-attachments/assets/d5ae3ca1-bef1-4f0b-938e-09fa8d6a52c8)
