### ISSUE TITLE
Unit is often not shown (when it is in front of the value?)

### ISSUE THREAD

**Issue by rrozema** [zeronounours/lovelace-energy-entity-row#5]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
1.0.0 through 1.1.0

**Last working release (if known):**
Never worked correctly

**Browser and Operating System:**
Android & Windows, chrome and edge, any version and combination I tried.

**Description of problem:**
When a unit is shown in front of the value -which is customary f.e. for currencies- that unit is shown only when the value is exactly 1 digit long. Like for example when the value is initially 0. When the value takes up more space, it looks like the value overwrites the unit.

![Screenshot_2024-12-09-10-40-50-355_io homeassistant companion android](https://github.com/user-attachments/assets/870ea4f2-6dca-41ad-8bd5-1e433a9ff960)
Each of the currency values in the above screenshot has a euro sign as its unit. The euro sign is however only shown when the value for that value is exactly 1 digit wide. And it disappears when the value changes to a wider value. I expect the unit to be shown on all fields.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by zeronounours** [comment]
I cannot get the same result with units shown the standard way:
![image](https://github.com/user-attachments/assets/facb75a7-6bfc-42c9-84a8-cdf8c728af40)

What customization are you using to show it at the beginning? Maybe I could make energy-entity-row compatible with it.

**Comment by rrozema** [comment]
To be honest I don't recall making any customizations in this area. I
suspect it is part of the settings i got when I selected my country and/or
language when setting up home assistant. For me that is Netherlands and
English. This is my settings -> system -> general screen:




Op wo 11 dec 2024 07:35 schreef Gauthier Sebaux ***@***.***>:

**Comment by zeronounours** [comment]
Strange. When changing the locale to the Netherlands, units still display correctly.
![image](https://github.com/user-attachments/assets/1c09c973-1971-4f1e-96fe-3e421f4f63e0)

Could you check the text being injected in the DOM using developer tools (Usually Ctrl+Shift+I):
- Is the unit missing in the text?
- Is it CSS issues with the box not being wide enough?

**Comment by zeronounours** [comment]
I think I've find the root cause of the issue. I have a similar behavior on my phone.

I think it relates to available Javascript APIs. Formatting use `Intl` API by default to format the value according to user's locale. I need to investigate further to see if and how I can remediate

**Comment by zeronounours** [comment]
@rrozema, I've implemented a fix which works on my devices with issues previously. Do you confirm it fixed it on yours too?

**Comment by rrozema** [comment]
Yes, with the latest version it is now OK in both windows and Android:
![image](https://github.com/user-attachments/assets/5ac17c24-1ffb-482b-8efa-cad53b6e4c41)
![image](https://github.com/user-attachments/assets/cc90d3c7-d599-45be-820a-67e0ad26dd7f)
